### ISSUE TITLE
Gestaltung von blockquote - Anführungszeichen oder nicht

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#10]
Bisher sind bei blockquote mal zusätzlich noch französische Anführungszeichen, mal nicht
- hier mit: http://dlina.github.io/presentations/2016-berlin/#/2/3 
- hier ohne: http://dlina.github.io/presentations/2016-berlin/#/4/2 und http://dlina.github.io/presentations/2016-berlin/#/4/3  

Müssen wir vereinheitlichen.

Ich würde plädieren für mit. @mathias-goebel und Du?

**Comment by mathias-goebel** [comment]
OK, dann bitte von nun an, innerhalb der blockquotes darauf verzichten, sie werden vom stylesheet immer gesetzt! css roxx!!!
