### ISSUE TITLE
Berlin Slide 4/2 - Änderungsvorschläge 

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#12]
@mathias-goebel 
![screenshot 4-2](https://cloud.githubusercontent.com/assets/12525907/12871860/22204e18-cd8e-11e5-8738-5e11be2ff3f8.jpeg)

• Passt bei mir nicht auf den Bildschirm (unten abgeschnitten, siehe Screenshot 4-2) 
• Literaturangaben kleiner? (z.B. wie auf http://dlina.github.io/presentations/2016-berlin/#/2/3 ) 
• sind unten noch notes eingeblendet? 
• ist es ok, wenn ich die Literaturangabe vereinheitliche?

**Comment by mathias-goebel** [comment]
sollte auch gar nicht da stehen, das ist mein ausformulierter vortrag, meine notes, abrufbar im "presenters view" (auf startseite taste "s" drücken...)

klar, literaturangaben immer vereinheitlichen, dazu kam ich die nacht nicht mehr.

**Comment by peertrilcke** [comment]
ok, dann kümmere ich mich gleich um die literaturangaben

**Comment by peertrilcke** [comment]
literaturangaben erledigt
