### ISSUE TITLE
Berlin Slide 4/3 - Korrekturvorschläge

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#13]
@mathias-goebel 
• Passt bei mir nicht auf den Bildschirm (unten abgeschnitten) 
• Literaturangaben kleiner? (z.B. wie auf http://dlina.github.io/presentations/2016-berlin/#/2/3 ) 
• sind unten noch notes eingeblendet? 
• statt englischer Anführungszeichen vielleicht »französische« 
• ok, wenn ich den Zitatnachweis vereinheitliche? 
![screenshot 4-3](https://cloud.githubusercontent.com/assets/12525907/12871870/6608a1b6-cd8e-11e5-8931-6081318428f8.jpeg)

**Comment by mathias-goebel** [comment]
ich mag die guillemets auch lieber, ich weiß nur nicht, wie ich sie über die tastatur eingebe...
notes sind raus.

**Comment by peertrilcke** [comment]
auf dem mac 
- öffnende: alt + umschalt + q
- schließende: alt + q
