### ISSUE TITLE
Berlin Slides 4/5

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#15]
@mathias-goebel 
• stark! 
• Passt bei mir nicht auf den Bildschirm (unten ist ein wenig Text abgeschnitten, siehe Screenshot 4-5) 
• Bildunterschrift etwas kleiner (oder sind das gar notes)? 
![screenshot 4-5](https://cloud.githubusercontent.com/assets/12525907/12871879/a3a08c96-cd8e-11e5-935b-3bce8aecc709.jpeg)

**Comment by mathias-goebel** [comment]
...es soll gar keine bildunterschrift geben, nur das video, meine notes sind also wieder raus.
