### ISSUE TITLE
Berlin Slide 4-6

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#17]
@mathias-goebel 
hier habe ich noch unten Abschnitt im Firefox 
![screenshot 4-6](https://cloud.githubusercontent.com/assets/12525907/12872069/3b3092ce-cd97-11e5-8e67-149939195397.jpeg)

**Comment by peertrilcke** [comment]
Vorschlag: ersten und zweiten Punkt als "Datenbestand und Aufgaben beliebig erweiterbar" zusammenfassen?

**Comment by mathias-goebel** [comment]
ie
