### ISSUE TITLE
Berlin Slide 4/1 

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#18]
@mathias-goebel 
nur falls das untergegangen sein sollte: hatte vorgeschlagen, immer mit ul bzw. Bulettpoints zu arbeiten, d.h. auch bei diesem Slide: http://dlina.github.io/presentations/2016-berlin/index.html#/4/1

Da hier ja aber tatsächlich ganze Sätze stehen, kann ich auch gut mit der p-Lösung leben.

**Comment by mathias-goebel** [comment]
Ich hatte diese Slide erst gar nicht vorgesehen, dann aber festgestellt, dass ich bis zur nächsten dann schon eine Minute sprechen werde. Die Slide dient also eher dem Betrachter der Slides, den Vortrag aus diesen nachverfolgen zu können und einen Übergang von Darios Part zu meinem zu schaffen. Ich würde sie stehen lassen, auch weil ich aus diesen Sätzen so schnell keine Liste machen kann, die genau das aussagt.

**Comment by peertrilcke** [comment]
leuchtet mir ein
