### ISSUE TITLE
aufräumen (last issue?) 

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#20]
sieht fertig aus, yeah. bin gerade auch noch 2x durchgegangen. 

wenn in der nächsten stunde kein einspruch von Dir kommt, würde ich noch die beiden von mir auskommentierten Stellen
index.html, Z. 77 und Z. 136-160 rausnehmen.

und dann ist alles schön! 

tausend thx, das war sehr produktiv!

**Comment by mathias-goebel** [comment]
Ich denke, das sieht sehr gut aus. Alles was auskommentiert ist, kann nun auch raus.

**Comment by peertrilcke** [comment]
great
