### ISSUE TITLE
keine kästen/rahmen was auch immer bei img

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#21]
hei. irgendwie gibt es so komische rahmen um grafiken, siehe z.B. hier: http://dlina.github.io/presentations/2016-leipzig/index.html#/2/4 

Hatte gehofft, ich kann das durch auskommentieren von Zeile 15-19 in der dlina.css (https://github.com/dlina/presentations/blob/gh-pages/2016-leipzig/dlina.css) killen, klappt aber irgendwie nicht.

**Comment by peertrilcke** [comment]
oh, sorry, klappt doch schon. aber jetzt ist noch ein schatten da. sollen wir den lassen (weil er vielleicht schön aussieht) oder auch noch weg nehmen (weil er blöd aussieht) und durch schmale border ersetzen?

**Comment by mathias-goebel** [comment]
Wenn es hier keine Meinung gibt, lassen wir es so.
