### ISSUE TITLE
BIldgröße in http://dlina.github.io/presentations/2016-leipzig/#/3/2

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#23]
@mathias-goebel @lehkost 
Könnte jemand das so einrichten, dass die beiden Bilddateien in der Folie die gleiche Höhe haben?

**Comment by mathias-goebel** [comment]
Alle?

**Comment by mathias-goebel** [comment]
Man müsste der Seite ne ID geben.

**Comment by peertrilcke** [comment]
in der index.html stehen die img in der zeile 157 und 158 - hilft das?

**Comment by peertrilcke** [comment]
perfekt!
