### ISSUE TITLE
letzte Grafik-Probleme bei http://dlina.github.io/presentations/2016-leipzig/#/4/17

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#24]
@mathias-goebel die Grafiken sind im Safari zerschossen, im Firefox nicht gleich groß. Sollten in beiden gleich groß sein (was sie von den Abmessungen eigentlich auch sind?)

**Comment by peertrilcke** [comment]
in diesem Fall ist es Zeile 436/437

**Comment by lehkost** [comment]
I think we can close this one…
