### ISSUE TITLE
Berlin Slide 5/2

### ISSUE THREAD

**Issue by peertrilcke** [dlina/presentations#7]
Nun Probleme in Safari, Firefox ok (aber Labels zu klein). 
<img width="1272" alt="bildschirmfoto 2016-02-07 um 11 03 06" src="https://cloud.githubusercontent.com/assets/12525907/12871773/ad9857a0-cd8a-11e5-919e-85da70d9089f.png">

**Comment by peertrilcke** [comment]
@mathias-goebel - Vorschlag: wir übernehmen diese nicht aus dem Blog, sondern ich baue sie kurz nach (dann auch ohne Libretto und ohne Other)

**Comment by mathias-goebel** [comment]
Uuuiiii, ja, klar: gerne nachbauen und so als png einbauen. geht immer!

**Comment by peertrilcke** [comment]
ok, wird gemacht - Schriftart der Slides ist SourceSansPro (brauchst nur reagieren, wenn nicht)

**Comment by peertrilcke** [comment]
wie wäre dieses png?
![berlin2016_fig-genre-density](https://cloud.githubusercontent.com/assets/12525907/12872009/a170edd4-cd94-11e5-905d-9da9b0a0689f.png)

**Comment by mathias-goebel** [comment]
ist drin!

**Comment by peertrilcke** [comment]
super
